### ISSUE TITLE
Server Console Spam

### ISSUE THREAD

**Issue by jermangarc** [notabadminer/UniversalCoinsMod#10]
I reported this on HoloInventory's Github, but I thought I'd let you know as well. Thanks.

https://github.com/dries007/HoloInventory/issues/12

**Comment by notabadminer** [comment]
This issue was my fault. The getInventoryName() function was using a method that worked internally, but did not play nice with holoinventory. I pushed an update with the fix. Download 1.7.10-1.6.12 from the releases page.
