### ISSUE TITLE
UniversalCoins-1.7.10-1.6.16 wants Minecraft 1.7.2

### ISSUE THREAD

**Issue by moTechPlz** [notabadminer/UniversalCoinsMod#11]
Hi, i installed 'UniversalCoins-1.7.10-1.6.16.jar', i get this message;
> Forge Mod Loader has found a problem with your minecraft installation
> The mod listed below does not want to run in Minecraft version 1.7.10
>   Universal Coins (universalcoins) wants Minecraft [1.7.2,1.7.2]

Not sure, the problem may be this; [https://github.com/notabadminer/UniversalCoinsMod/blob/master/java/universalcoins/UniversalCoins.java#L67](https://github.com/notabadminer/UniversalCoinsMod/blob/master/java/universalcoins/UniversalCoins.java#L67).

**Comment by jermangarc** [comment]
Same here, downloaded 1.7.10 version.

**Comment by spannerman79** [comment]
Also same here.  Double checked to ensure I downloaded the correct one just in case it was an issue on my end.

**Comment by notabadminer** [comment]
I forgot to change a couple lines that restrict which version the mod will run on. The .17 versions are correct. The 1.7.2-1.6.17 version is set to run on both 1.7.2 and 1.7.10. I will do some testing and make sure it works alright so I can do one 1.7 and one 1.8 release going forward. Sorry about the mixup.
