### ISSUE TITLE
Ticking block entity 1.7.10-1.6.22

### ISSUE THREAD

**Issue by codejam1024** [notabadminer/UniversalCoinsMod#12]
Time: 7/11/15 11:19 AM
Description: Ticking block entity

java.lang.NullPointerException: Ticking block entity
	at universalcoins.tile.TileVendor.getOwnerAccountBalance(TileVendor.java:991)
	at universalcoins.tile.TileVendor.activateSellButton(TileVendor.java:118)
	at universalcoins.tile.TileVendor.func_145845_h(TileVendor.java:91)
	at net.minecraft.world.World.func_72939_s(World.java:2512)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:669)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:954)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:809)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:669)
	at java.lang.Thread.run(Unknown Source)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at universalcoins.tile.TileVendor.getOwnerAccountBalance(TileVendor.java:991)
	at universalcoins.tile.TileVendor.activateSellButton(TileVendor.java:118)
	at universalcoins.tile.TileVendor.func_145845_h(TileVendor.java:91)

-- Block entity being ticked --
Details:
	Name: TileVendorBlock // universalcoins.tile.TileVendorBlock
	Block type: ID #665 (tile.blockVendor // universalcoins.blocks.BlockVendor)
	Block data value: 4 / 0x4 / 0b0100
	Block location: World: (-76,70,193), Chunk: (at 4,4,1 in -5,12; contains blocks -80,0,192 to -65,255,207), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Actual block type: ID #665 (tile.blockVendor // universalcoins.blocks.BlockVendor)
	Actual block data value: 4 / 0x4 / 0b0100
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:2512)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:669)

-- Affected level --
Details:
	Level name: world
	All players: 1 total; [EntityPlayerMP['jam1024'/128, l='world', x=-73.70, y=69.00, z=192.93](jam1024 at -73.69565721694836,69.0,192.92727451234197)]
	Chunk stats: ServerChunkCache: 625 Drop: 0
	Level seed: 4378077409963410617
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: 
	Level spawn location: World: (-102,65,198), Chunk: (at 10,4,6 in -7,12; contains blocks -112,0,192 to -97,255,207), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 60807 game time, 73279 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 63548 (now: false), thunder time: 13509 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:954)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:809)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:669)
	at java.lang.Thread.run(Unknown Source)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 8.1 (x86) version 6.3
	Java Version: 1.8.0_45, Oracle Corporation
	Java VM Version: Java HotSpot(TM) Client VM (mixed mode), Oracle Corporation
	Memory: 176593232 bytes (168 MB) / 465010688 bytes (443 MB) up to 760217600 bytes (725 MB)
	JVM Flags: 2 total; -Xms450M -Xmx750M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 96
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1448 30 mods loaded, 30 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{7.10.99.99} [Forge Mod Loader] (KCauldron-1.7.10-1448.121-server.jar) 
	UCHIJAAAA	Forge{10.13.4.1448} [Minecraft Forge] (KCauldron-1.7.10-1448.121-server.jar) 
	UCHIJAAAA	kimagine{0.1} [KImagine] (minecraft.jar) 
	UCHIJAAAA	CodeChickenCore{1.0.7.45} [CodeChicken Core] (minecraft.jar) 
	UCHIJAAAA	uniskinmod{1.2-dev4} [Universal Skin Mod] (minecraft.jar) 
	UCHIJAAAA	AppleCore{1.1.0} [AppleCore] (AppleCore-mc1.7.10-1.1.0.jar) 
	UCHIJAAAA	Backpack{2.0.1} [Backpack] (backpack-2.0.1-1.7.x.jar) 
	UCHIJAAAA	BuildCraft|Core{7.0.13} [BuildCraft] (buildcraft-7.0.13.jar) 
	UCHIJAAAA	BuildCraft|Silicon{7.0.13} [BC Silicon] (buildcraft-7.0.13.jar) 
	UCHIJAAAA	BuildCraft|Transport{7.0.13} [BC Transport] (buildcraft-7.0.13.jar) 
	UCHIJAAAA	BuildCraft|Builders{7.0.13} [BC Builders] (buildcraft-7.0.13.jar) 
	UCHIJAAAA	BuildCraft|Robotics{7.0.13} [BC Robotics] (buildcraft-7.0.13.jar) 
	UCHIJAAAA	BuildCraft|Energy{7.0.13} [BC Energy] (buildcraft-7.0.13.jar) 
	UCHIJAAAA	BuildCraft|Factory{7.0.13} [BC Factory] (buildcraft-7.0.13.jar) 
	UCHIJAAAA	ChickenChunks{1.3.4.19} [ChickenChunks] (ChickenChunks-1.7.10-1.3.4.19-universal.jar) 
	UCHIJAAAA	IC2{2.2.747-experimental} [IndustrialCraft 2] (industrialcraft-2-2.2.747-experimental.jar) 
	UCHIJAAAA	mobends{0.20.1} [Mo' Bends] (MoBends-0.20.1 for MC 1.7.10.jar) 
	UCHIJAAAA	Baubles{1.0.1.10} [Baubles] (Baubles-1.7.10-1.0.1.10.jar) 
	UCHIJAAAA	Thaumcraft{4.2.3.5} [Thaumcraft] (Thaumcraft-1.7.10-4.2.3.5.jar) 
	UCHIJAAAA	harvestcraft{1.7.10i} [Pam's HarvestCraft] (Pam's HarvestCraft 1.7.10i.jar) 
	UCHIJAAAA	SGCraft{1.9.3} [Greg's SG Craft] (SGCraft-1.9.3-mc1.7.10.jar) 
	UCHIJAAAA	SpiceOfLife{1.2.3} [The Spice of Life] (SpiceOfLife-mc1.7.10-1.2.3.jar) 
	UCHIJAAAA	universalcoins{1.7.10-1.6.22} [Universal Coins] (UniversalCoins-1.7.10-1.6.22.jar) 
	UCHIJAAAA	warpbook{2.0.null} [Warp Book] (warpbook-1.7.10_2.0.36.jar) 
	UCHIJAAAA	ForgeMultipart{1.2.0.345} [Forge Multipart] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
	UCHIJAAAA	McMultipart{1.2.0.345} [Minecraft Multipart Plugin] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
	UCHIJAAAA	HungerOverhaul{1.7.10-1.0.0.jenkins75} [Hunger Overhaul] (HungerOverhaul-1.7.10-1.0.0.jar) 
	UCHIJAAAA	ForgeMicroblock{1.2.0.345} [Forge Microblocks] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Player Count: 1 / 20; [EntityPlayerMP['jam1024'/128, l='world', x=-73.70, y=69.00, z=192.93](jam1024 at -73.69565721694836,69.0,192.92727451234197)]
	Is Modded: Definitely; Server brand changed to 'kcauldron,cauldron,craftbukkit,mcpc,fml,forge'
	Type: Dedicated Server (map_server.txt)

**Comment by codejam1024** [comment]
because seller is no money?

**Comment by notabadminer** [comment]
Fixed with 1.7.x-1.6.23 releases.
