### ISSUE TITLE
UC price files in wrong location

### ISSUE THREAD

**Issue by Higgs1** [notabadminer/UniversalCoinsMod#17]
Hello!

I'd like to suggest a feature and/or bug fix: Could you please move the UC price files to Forge's config directory? ({gamedir}/config/universalcoins instead of ./config/universalcoins) 

I recently recieved a mod pack from a friend, and thought the prices were way off but it turns out it wasn't reading from his price files, since he had them in {gamedir}/config/universalcoins, but my Minecraft instance was looking for them at ./config/universalcoins (where it generated the default price files).

Thanks :D

**Comment by notabadminer** [comment]
The config files should be in {gamedir}/config/universalcoins. I've run on Windows and Linux without issues. What OS and Java version are you using? Are you using a custom launcher?

**Comment by Higgs1** [comment]
I'm on Linux, OpenJDK, and yes a custom 'launcher'. But in the code...
https://github.com/notabadminer/UniversalCoinsMod/blob/master/java/universalcoins/util/UCItemPricer.java#L42
```java
private static String configDir = "." + File.separatorChar + "config" + File.separatorChar + "universalcoins" + File.separatorChar;
```
It specificly points to ./config/universalcoins, and not {gamedir}. Other mods put their config files in {gamedir}/config somehow, so I thought it would be a fairly simple change that I think would be a really great addition to your mod.
Mods that use {gamedir}/config:
* Applied Energistics 2
* Archimedes Ships
* Big Reactors
* Big Trees
* Enchiridion
* Buildcraft
* Chocolate Quest
* COFH's mods
* Custom Ore Gen
* EnderIO
* Hunger Overhaul
* More Pistons
* Mekanism
* Metallurgy
* Mine Menu
* NEI
* Open Computers
* Plant Megapack
* Power Converters
* Power Crystals
* Railcraft
* Reika's mods
* Slime Knights
* Spice of Life
* Custom Configs
Mods that use ./config:
* Ancient Warfare
* Universal Coins

**Comment by Higgs1** [comment]
Hi again... I looked it up and it turns out Forge tells you what directory you can dump your config files in, which is even better! I believe the correct code is

```java
new File(event.getModConfigurationDirectory(), "Folder name, such as the modID");
```

This also allows you to watch for config file updates too (if you're not already doing that? I haven't checked actually >.<)

```java
 @SubscribeEvent
public void onConfigFileChanged(ConfigFileChangedEvent event) {
    //update prices please so that I don't have to restart every time!!!! Thanks :D
}
```

**Comment by Higgs1** [comment]
Hi, me again! I looked it up and there is a specific directory Forge has for dumping config things, it's FMLPreInitializationEvent.getModConfigurationDirectory()
http://cmicro.github.io/NeatCraft/forge-javadoc/cpw/mods/fml/common/event/FMLPreInitializationEvent.html#getModConfigurationDirectory%28%29

**Comment by notabadminer** [comment]
With the unmodified launcher, "."  is the minecraft folder. Which is why using the code config/universalcoins was used. I wasn't aware of any issues as I haven't used any other launchers. I will change the code to match how NEI gets the config dir and it should resolve the issue.
NEI uses `FMLInjectionData.data()[6]` which returns the Minecraft home dir.

The new line will be:
`private static String configDir = FMLInjectionData.data()[6] + "/config/universalcoins/";`

**Comment by Higgs1** [comment]
Thanks! That code looks pretty nifty. Now I can just drag and drop one config directory when I get an update from my friends. 

Now I'll just need to message the AW2 devs. Maybe they'll use that line of code too.
