### ISSUE TITLE
Packager Negative Balance

### ISSUE THREAD

**Issue by Cobra1117** [notabadminer/UniversalCoinsMod#23]
If you apply a redstone signal to a packager when it has no coins, the coin balance will go negative. Attempting to add coins at this point results in a dupe bug. (When you take the coins back out of the left slot, it returns ~25,000 of whatever type of coin you put in.)

**Comment by Cobra1117** [comment]
Tested with 1.7.10-1.6.35

**Comment by notabadminer** [comment]
fixed with latest push. Fix will be in next update.
