### ISSUE TITLE
Buying with a credit card causes negative balance

### ISSUE THREAD

**Issue by Cobra1117** [notabadminer/UniversalCoinsMod#24]
If you set up a vendor with a credit card in it (to automatically receive the money) and someone buys with a credit card, the balance on the vending block becomes negative. Attempting to add coins at this point results in a dupe bug. (When you take the coins back out of the left slot, it returns ~25,000 of whatever type of coin you put in.) This may be related to issue #23 .

**Comment by Cobra1117** [comment]
Tested with 1.7.10-1.6.35

**Comment by notabadminer** [comment]
This should be fixed with the latest push. Fix will be included in next release.
