### ISSUE TITLE
Advanced Sign (still) does not support credit card buys correctly

### ISSUE THREAD

**Issue by Cobra1117** [notabadminer/UniversalCoinsMod#31]
Issue #26 mostly fixed the problem, but there's still a minor bug:

* Place an advanced sign
* Set up a vending block to buy items
* Add a credit card
* Close the GUI
* Open the GUI
* Close the GUI
* The sign now reads "Out Of Coins!"

(In other words, opening the GUI and not changing anything causes it to think it's out of coins)

**Comment by notabadminer** [comment]
This issue should be resolved with 1.7.x-1.6.38 release.
