### ISSUE TITLE
[Enhancement] Selling Catalogue displays all trades

### ISSUE THREAD

**Issue by Alaberti** [notabadminer/UniversalCoinsMod#33]
Would it be possible to have the selling catalogue display a list of all trades available from vending blocks and frames and such? Kinda like the catalogue from Forestry for trade stations? Possibly, with a config option, allow remote purchases?

**Comment by spannerman79** [comment]
For suggestions on crafting have it shapeless with the catalogue plus ender card  (NBT tagged to intended player)
