### ISSUE TITLE
NEI Vending Frame Recipe Missing 

### ISSUE THREAD

**Issue by ArmandVestibule** [notabadminer/UniversalCoinsMod#34]
In the current and previous stable releases, the recipe for the Vending Frame seems to be missing and I don't see a recipe for it published on official mod pages. Is this by design? Is there a way we can get the recipe published somewhere in the meantime?

Thanks!

**Comment by notabadminer** [comment]
The recipe should be: 
stick, gold ingot, stick
redstone dust, planks, redstone dust
stick, stick, stick

NEI will not show the recipe since it is a custom one that does special things. Craftguide should work since I did do some work on integration for that mod.

**Comment by ArmandVestibule** [comment]
Understood. Thanks!
