### ISSUE TITLE
[1.8.9] Storage Linking Card Broken

### ISSUE THREAD

**Issue by Cobra1117** [notabadminer/UniversalCoinsMod#38]
In 1.8.9-0.4, remote linking cards don't work correctly. After shift-right clicking a chest, you get the expected message ("Location stored: x y z"), but the card doesn't display the stored location and can't be used to link to a vending block.

**Comment by notabadminer** [comment]
I fixed the issue and added a couple other tweaks. https://github.com/notabadminer/UniversalCoins/releases

**Comment by Cobra1117** [comment]
Fix confirmed. Thanks!
