### ISSUE TITLE
Universal ATM DUPE!

### ISSUE THREAD

**Issue by Radviger** [notabadminer/UniversalCoinsMod#7]
Hi, notabadminer. On this week i found that some players get duped diamond blocks on my server. Today my friend found this video on youtube:
http://www.youtube.com/watch?v=25r0FihyeBA
I've saw that Universal ATM will DUPE items if I place stackable items in top left five slots on my inventory and SHIFT+Left Click on first of it they will stack to 64. Its so TERRIBLE! Please FIX IT!

**Comment by Radviger** [comment]
Screenshots:
BEFORE: http://pixs.ru/showimage/duppng_6466071_15939351.png
AFTER: http://pixs.ru/showimage/dupecoplit_6809094_15939357.png

**Comment by notabadminer** [comment]
Which version are you running? I recall this being an issue, but I thought it was fixed with an update.

**Comment by Radviger** [comment]
Ok, I've updated mod to latest version and I've found that you fixed that bug. Really nice.
Here is updated version of languages and textures:
http://pastebin.com/jtRCHA68
http://pastebin.com/cgdSLyu2
Textures: https://www.dropbox.com/s/hn40ad031mfnsx5/textures.zip?dl=0
I've changed money types like this:
Coin, Coin Stack, Dollar, Dollar Stack, Money Bag

**Comment by notabadminer** [comment]
I just updated with a release that doesn't crash the server when crafting a Vending Frame. I'm still not sure about changing to the different money types. I am leaning towards keeping the generic coin types. I do like the textures though. They are cleaner than the stuff I threw together. At the least, I will update the russian lang and give you credit.

**Comment by Radviger** [comment]
I think that new money types will be better, also for them exists textures.
But you can make banknote instead of dollar (Just rename it in Lang)

**Comment by Radviger** [comment]
Its will be nice 😁
