### ISSUE TITLE
Support for AE2?

### ISSUE THREAD

**Issue by jermangarc** [notabadminer/UniversalCoinsMod#8]
Hello, just installed your mod on out private clan server, gotta say it's one cool mod. A great replacement to our old Bukkit Vault system we had on Cauldron. Not sure if this is really a bug report, rather an FYI.

One of the admins installed his Safe in his base, and had an export bus hooked up to it from his AE system. The server crashed as soon as the AE system tried to put coins in the safe. Here is the crash log. http://pastebin.com/k5YQwtwr

From what I can deduce the safe didn't know which account to assign the coins to when the player was offline.

**Comment by notabadminer** [comment]
The safe has a function that looks up the player UUID. I think this is
causing the crash. I'll modify the code so it looks it up once when the
player places the safe and store the value instead.

The fix shouldn't take too long. I'll try to get it completed tomorrow.
On Feb 23, 2015 6:20 PM, "Jermaine Garcia" <notifications@github.com> wrote:

Hello, just installed your mod on out private clan server, gotta say it's
one cool mod. A great replacement to our old Bukkit Vault system we had on
Cauldron. Not sure if this is really a bug report, rather an FYI.

One of the admins installed his Safe in his base, and had an export bus
hooked up to it from his AE system. The server crashed as soon as the AE
system tried to put coins in the safe. Here is the crash log.
http://pastebin.com/k5YQwtwr

From what I can deduce the safe didn't know which account to assign the
coins to when the player was offline.

—
Reply to this email directly or view it on GitHub
<https://github.com/notabadminer/UniversalCoinsMod/issues/8>.

**Comment by notabadminer** [comment]
The 1.7.X-1.6.4 release fixes this issue

**Comment by jermangarc** [comment]
Thank you, i will have him try it out. Thanks again!

**Comment by jermangarc** [comment]
Just wanted to let you know that it worked like a charm. Thanks a bunch!
